// Тела крипов
const BODY_3_WORKER = [WORK, CARRY, MOVE];
const BODY_550P_WORKER = [WORK, MOVE, CARRY, WORK, CARRY, WORK, CARRY, MOVE];
const BODY_1000P_WORKER = [WORK, MOVE, CARRY, WORK, MOVE, CARRY, WORK, MOVE, CARRY, CARRY, CARRY, MOVE, CARRY, WORK, CARRY, MOVE];
const BODY_300P_DEFENDER = [TOUGH, TOUGH, WORK, CARRY, ATTACK, MOVE];
const BODY_550P_DEFENDER = [TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, CARRY, CARRY, WORK, ATTACK, ATTACK, MOVE];
const BODY_600P_DEFENDER = [TOUGH, TOUGH, TOUGH, TOUGH, WORK, CARRY, WORK, CARRY, MOVE, ATTACK, ATTACK, MOVE];
const CLAIMER_650P_CREEP = [CLAIM, MOVE, MOVE];
const CLAIMER_1800P_CREEP = [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, CLAIM, MOVE, MOVE];
const T1000 = [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, MOVE, MOVE];
const BODY_1000P_HEALER = [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, MOVE];
const BODY_150P_LOGIST = [CARRY, CARRY, MOVE];
const BODY_300P_LOGIST = [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE];
const BODY_550P_LOGIST = [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE];

const CREEPS_BODIES = {
    worker: [BODY_3_WORKER, BODY_550P_WORKER, BODY_1000P_WORKER],
    defender: [BODY_300P_DEFENDER, BODY_550P_DEFENDER, BODY_600P_DEFENDER, T1000],
    claimer: [CLAIMER_650P_CREEP, CLAIMER_1800P_CREEP],
    healer: [BODY_1000P_HEALER],
    logist: [BODY_150P_LOGIST, BODY_300P_LOGIST, BODY_550P_LOGIST]
};

// Стоимость частей тела
const BODYPART_COST = {
    "move": 50, 
    "work": 100,
    "attack": 80,
    "carry": 50,
    "heal": 250,
    "ranged_attack": 150,
    "tough": 10,
    "claim": 600
};

// Желаемое количество крипов по ролям
const DESIRED_COUNTS = {
    harvester: 6,
    upgrader: 5,
    builder: 5,
    defender: 5,
    guardian: 1,
    claimer: 1,
    healer: 1,
    towerman: 1,
    hardvester: 2,
    logist: 2
};

const LINKS_ID = {
    Spawn1: {
        sourceId: '68c038b470da6d0069d3c36c',
        targetId: '68c026df04d00b0044561955'
    },
    E19S1SPAWN1: {
        sourceId: 'SOURCE_LINK_ID_HERE',
        targetId: 'TARGET_LINK_ID_HERE'
    }
};

module.exports = {
    CREEPS_BODIES,
    BODYPART_COST,
    DESIRED_COUNTS,
    LINKS_ID
};
